### ISSUE TITLE
New Version completely broke workflow

### ISSUE THREAD

**Issue by benkaiser** [OpenSilk/Orpheus#15]
Hey,

I've got my own open source web-based music player called [node music player](https://github.com/benkaiser/node-music-player). I don't have a native Android companion for it yet, but I figured since Android has an internal storage of playlists and songs, I don't need to! all I needed was a sync application, called !node music player sync](https://github.com/benkaiser/android-node-music-sync). This has worked great for previous versions of Orpheus because it used the system song index and playlists.

The new version however, is crap. Like even without my workflow, what about all the users that had carefully curated a bunch of playlists? You'll just tell them Orpheus doesn't use them anymore and ignore them?

There seriously need to be a feature to sync up with internal songs and playlists, like a migrator. That optimally (for my use case, does not apply to everyone) can be re-run at any point in time.

For now in downgrading to Orpheus 2, I don't have time to rebuild all my thousands of songs into the exact same playlists again.

**Comment by drewis** [comment]
This is the best i can do for now https://github.com/OpenSilk/Orpheus/commit/adfb14262ceda17e472394bd0e1ffbc2df334b8a Ill start working on fixing playlist support for 3.1. 

Your node player looks like something id like Orpheus to support through a plugin. I didn't look but as long as it has an api to list folders/playlists and endpoints to download tracks with range support. Since you have a sync app i assume it does. 

As far as syncing. something ive been wanting to add was a way to import or pin music locally, but havent figured out how to implement it.

**Comment by benkaiser** [comment]
Okay, so just having a quick look at that code does that only allow you to import them? Or does it actually construct Orpheus playlists from the android playlists?

First issue with the plugin idea may be that my music player actually communicates via websockets (socket.io specifically) for all metadata, then via http for the raw song and coverart files. I guess if we could find / decide on a standard I would be happy making that available in my music player.
I do feel however that it's a bit of a step in the wrong direction, as it would be tightly coupling the two music players, whereas we would like to keep it as open as possible.

I propose that in Orpheus, there be a service that monitors for playlist changes at the system level, then updates the Orpheus playlists in the event they differ (if there is a song in a system playlist but not in the Orpheus version but Orpheus has already imported that track before, the user has most likely removed the track from the playlist in Orpheus, so don't add them in that case).

This service could run in the background every time the Orpheus activity comes into the foreground.

Alternatively I guess it's just time for me to bite the bullet and write my own android front-end to node music player.

**Comment by benkaiser** [comment]
I guess with regards to plugins, the plugin could just be one that syncs with androids internal playlists / song database. That would be fine / would fix the workflow.

**Comment by drewis** [comment]
The commit only lets you view the playlists from the folders ui. You can (hackily) import them manually by indexing the folders containing the music. Then playing the playlist and saving the queue. Which will just make a copy in orpheus' database.

**Comment by benkaiser** [comment]
New update is great. Thank you so much for adding back in native playlist support. You rock dude!
