### ISSUE TITLE
Multi-cd compilations and ordering

### ISSUE THREAD

**Issue by abouteiller** [OpenSilk/Orpheus#19]
Since update 3.x, multi-cd compilations are not  handled properly. 

I have two directories for that same album. one contains cd1, the other cd2

Id3 tag contains 
track 1
cd 1 
track name foo
album name bar

track 1
cd 2
track name foo2
album name bar

The two directories are mangled together (which is fine and even a welcome improvement), however, the track ordering does not respect the "cd" id3 tag, hence the general ordering is wrong

track1 (cd1), track1 (cd2), track 2(cd1), track2 (cd2), etc.

**Comment by abouteiller** [comment]
Thanks for fixing it that quick!

**Comment by drewis** [comment]
Thanks for reporting
