### ISSUE TITLE
skipping next and previous via bluetooth

### ISSUE THREAD

**Issue by benkaiser** [OpenSilk/Orpheus#5]
Hello,

I recently tried out Orpheus as I saw it was open source and looked way better than the UI of apollo, however there are a few key functions I've found missing:
1. ~~Seeking within a song~~ (edit: work this out too, have to long press the cover art, can be configured in settings)
2. Next and previous via bluetooth ([guessing the source is here](https://github.com/OpenSilk/Orpheus/blob/a0cb70edb8d08a5a8a23ea68b2b77d1ff0b05402/app/src/main/java/com/andrew/apollo/MusicPlaybackService.java#L1001))
3. ~~Next and previous buttons in the app~~ (edit: worked this out, have to long-press the play button, can be configured in settings)

If these are already implemented can you let me know how to access them?

Cheers

**Comment by benkaiser** [comment]
Also more resources for the broadcastreceiver used for bluetooth commands: http://stackoverflow.com/a/8074401/485048

**Comment by laydros** [comment]
For #1 & #3 there is a pair of arrows in the top right corner of the now
playing art that reveal track controls and a round seeking bar.
On Apr 26, 2015 8:16 PM, "Benjamin Kaiser" notifications@github.com wrote:

Hello,

I recently tried out Orpheus as I saw it was open source and looked way
better than the UI of apollo, however there are a few key functions I've
found missing:
- Seeking within a song
- Next and previous via bluetooth (guessing the source is here
  https://github.com/OpenSilk/Orpheus/blob/a0cb70edb8d08a5a8a23ea68b2b77d1ff0b05402/app/src/main/java/com/andrew/apollo/MusicPlaybackService.java#L1001
  )
- Next and previous buttons in the app

If these are already implemented can you let me know how to access them?

Cheers

—
Reply to this email directly or view it on GitHub
https://github.com/OpenSilk/Orpheus/issues/5.

**Comment by benkaiser** [comment]
Thanks @laydros . Now the only think I'm still having issues with are the bluetooth playback not supporting the next and previous commands.

**Comment by benkaiser** [comment]
All good. This works. It just sometimes has an issue where the track will play silently until I click next or previous, but this is a minor issue and I'm not too worried about it.
