### ISSUE TITLE
Shuffle all songs

### ISSUE THREAD

**Issue by benkaiser** [OpenSilk/Orpheus#8]
When clicking on a track in the songs tab, it adds only that specific song to the queue. Is there a way to add all the songs in the library to the queue and play them on shuffle?

I hop in my car and often just want to listen to everything on shuffle as I want to avoid interaction with my phone while driving but there is not currently a way I have found that allows me to do this.

**Comment by drewis** [comment]
Currently (in 2.x) the auto shuffle will do this. Clicking the shuffle button in the action bar when in 'my library'. In the upcoming 3.0 i have made some changes to how the queue works, and it will behave as you describe (but 3.0 is still a ways off)

**Comment by benkaiser** [comment]
I completely missed that button! But yeah it works perfectly :+1:

Thanks for all your work on Orpheus, it really is a much nicer music player than Apollo :)
